name: Release
on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  id-token: write
  packages: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changeset.outputs.published }}
      publishedPackages: ${{ steps.changeset.outputs.publishedPackages }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.6

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Create Release Pull Request
        id: changeset
        uses: changesets/action@v1
        with:
          commit: "release: version packages"
          publish: pnpm run publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  packages_to_build:
    name: Get Released Packages
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.published == 'true' }}
    outputs:
      packages: ${{ steps.packages.outputs.PACKAGES }}
    steps:
      - name: Get released packages
        id: packages
        run: |
          echo "PACKAGES=$(jq -c '[ .[].name ]' <(echo '${{ needs.release.outputs.publishedPackages }}'))" >> "$GITHUB_OUTPUT"

  build_docs:
    name: Build Docs
    needs: [release, packages_to_build]
    if: ${{ needs.release.outputs.published == 'true' && contains(fromJSON(needs.packages_to_build.outputs.packages), 'docs') }}
    uses: ./.github/workflows/docs.yaml
#   build_web:
#     name: Build Web
#     needs: [release, packages_to_build]
#     if: ${{ needs.release.outputs.published == 'true' && contains(fromJSON(needs.packages_to_build.outputs.packages), 'web') }}
#     uses: ./.github/workflows/web.yaml
